### ISSUE TITLE
EdisonCore-1.3.1.1 fails to build with GHC >= 8.4

### ISSUE THREAD

**Issue by andreasabel** [robdockins/edison#22]
EdisonCore-1.3.1.1 fails to build with GHC 8.4 or newer because of the new `Semigroup` superclass requirement for `Monoid`.
```
$ cabal build -O0 -w ghc-8.4.4
...
Building library for EdisonCore-1.3.1.1..
...
[ 3 of 26] Compiling Data.Edison.Seq.BraunSeq ( src/Data/Edison/Seq/BraunSeq.hs, /Users/abel/tmp/trustee/EdisonCore-1.3.1.1/dist-newstyle/build/x86_64-osx/ghc-8.4.4/EdisonCore-1.3.1.1/noopt/build/Data/Edison/Seq/BraunSeq.o )

src/Data/Edison/Seq/BraunSeq.hs:563:10: error:
    • No instance for (Semigroup (Seq a))
        arising from the superclasses of an instance declaration
      There are instances for similar types:
        instance Semigroup (Data.Sequence.Internal.Seq a)
          -- Defined in ‘Data.Sequence.Internal’
    • In the instance declaration for ‘Monoid (Seq a)’
    |
563 | instance Monoid (Seq a) where
    |          ^^^^^^^^^^^^^^
```
I "fixed" this in https://hackage.haskell.org/package/EdisonCore-1.3.1.1/revisions/ with new constraint `base < 4.11`.

**Comment by andreasabel** [comment]
I also fixed the `base` upper bound for 1.3 and 1.3.1.
