### ISSUE TITLE
EdisonCore-1.3.1.1 fails to build with GHC 8.0.2

### ISSUE THREAD

**Issue by andreasabel** [robdockins/edison#21]
EdisonCore-1.3.1.1 misses some bounds on its dependency, so build broke:
```
$ cabal install -w ghc-8.0.2 EdisonCore-1.3.1.1
...
Building library for EdisonCore-1.3.1.1..
[ 1 of 26] Compiling Data.Edison.Seq.Defaults ( src/Data/Edison/Seq/Defaults.hs, dist/build/Data/Edison/Seq/Defaults.o )

src/Data/Edison/Seq/Defaults.hs:203:39: error:
    • Could not deduce (Control.Monad.Fail.MonadFail Identity)
        arising from a use of ‘lookupM’
      from the context: Sequence s
        bound by the type signature for:
                   lookupUsingLookupM :: Sequence s => Int -> s a -> a
        at src/Data/Edison/Seq/Defaults.hs:202:1-51
    • In the first argument of ‘runIdentity’, namely ‘(lookupM i s)’
      In the expression: runIdentity (lookupM i s)
      In an equation for ‘lookupUsingLookupM’:
          lookupUsingLookupM i s = runIdentity (lookupM i s)
```
Nearby Edison versions (1.3.x) have similar problems.

**Comment by andreasabel** [comment]
`trustee sweep` gives the following valid dependency ranges for compilation under GHC 8.0.2:
```
            8.0.2                 
EdisonAPI   1.3.3                 
QuickCheck  2.8.2 .. 2.14.2 (24)  
array       0.5.1.1 .. 0.5.4.0 (4)
base        4.9.1.0               
containers  0.5.7.0 .. 0.6.6 (15) 
mtl         2.2.1, 2.2.2        
```

**Comment by Lysxia** [comment]
Done. Agda-2.5.2 seems to be building again.

**Comment by andreasabel** [comment]
Excellent, thanks!
